export enum BDStage
{
	"Cold" = "Cold",
	"Parking Lot" = "Parking Lot",
	"In Pursuit" = "In Pursuit",
	"Meeting Conducted" = "Meeting Conducted",
	"Survey Submitted" = "Survey Submitted",
	"Contract Issued" = "Contract Issued",
	"Signature Pending" = "Signature Pending",
	"Contract Signed" = "Contract Signed",
	"Prospecting" = "Prospecting",
	"Recycle" = "Recycle",
	"Qualified" = "Qualified",
	"Opportunity Transferred" = "Opportunity Transferred",
	"Registered" = "Registered",
	"Paid" = "Paid",
	"Signed T&C" = "Signed T&C",
	"Cancelled" = "Cancelled",
	"Target" = "Target",
	"Closed Lost" = "Closed Lost",
	"Budget Reminder" = "Budget Reminder",
	"Discovery call" = "Discovery call",
	"Renewal Presentation" = "Renewal Presentation",
	"Renewal Negotiation" = "Renewal Negotiation",
}