import { Country } from './country';

export const CountryAndStates: { [key in Country]?: string[] } =
{
	"United States": [
		"Alabama",
		"Alaska",
		"Arizona",
		"Arkansas",
		"California",
		"Colorado",
		"Connecticut",
		"Delaware",
		"District of Columbia",
		"Florida",
		"Georgia",
		"Hawaii",
		"Idaho",
		"Illinois",
		"Indiana",
		"Iowa",
		"Kansas",
		"Kentucky",
		"Louisiana",
		"Maine",
		"Montana",
		"Nebraska",
		"Nevada",
		"New Hampshire",
		"New Jersey",
		"New Mexico",
		"New York",
		"North Carolina",
		"North Dakota",
		"Ohio",
		"Oklahoma",
		"Oregon",
		"Maryland",
		"Massachusetts",
		"Michigan",
		"Minnesota",
		"Mississippi",
		"Missouri",
		"Pennsylvania",
		"Rhode Island",
		"South Carolina",
		"South Dakota",
		"Tennessee",
		"Texas",
		"Utah",
		"Vermont",
		"Virginia",
		"Washington",
		"West Virginia",
		"Wisconsin",
		"Wyoming",
	],
	"Canada": [
		"Alberta",
		"British Columbia",
		"Manitoba",
		"New Brunswick",
		"Newfoundland and Labrador",
		"Nova Scotia",
		"Ontario",
		"Prince Edward Island",
		"Quebec",
		"Saskatchewan",
		"Northwest Territories",
		"Nunavut",
		"Yukon",
	],
	"United Kingdom": [
		"London - Canary Wharf",
		"London - City",
		"London - City Fringe",
		"London - Midtown",
		"London - Southbank",
		"London - West End",
		"London - Other",
		"East Midlands",
		"North-East",
		"North-West",
		"Scotland",
		"South-East",
		"South-West",
		"Wales",
		"West Midlands",
		"Yorkshire and the Humber",
		"East Anglia",
	],
	"Germany": [
		"Baden - Württemberg",
		"Bayern",
		"Berlin",
		"Brandenburg",
		"Bremen",
		"Hamburg",
		"Hessen",
		"Mecklenburg - Vorpommern",
		"Niedersachsen",
		"Nordrhein - Westfalen",
		"Rheinland - Pfalz",
		"Saarland",
		"Sachsen",
		"Sachsen - Anhalt",
		"Schleswig - Holstein",
		"Thüringen",
	],
	"France": [
		"Auvergne-Rhône-Alpes",
		"Bourgogne-Franche-Comté",
		"Bretagne",
		"Centre-Val de Loire",
		"Corse",
		"Grand Est",
		"Hauts-de-France",
		"Ile-de-France",
		"Normandie",
		"Nouvelle-Aquitaine",
		"Occitanie",
		"Pays de la Loire",
		"Provence-Alpes-Côte d'Azur",
	],
}