import { Country } from './country';

export const CountryCode: Record<Country, string> & Record<string, string> = {
	"APAC - Other": "APACO",
	"Afghanistan": "AF",
	"Aland Islands": "AX",
	"Albania": "AL",
	"Algeria": "DZ",
	"Andorra": "AD",
	"Angola": "AO",
	"Anguilla": "AI",
	"Antarctica": "AQ",
	"Antigua&Barbuda": "AG",
	"Argentina": "AR",
	"Armenia": "AM",
	"Aruba": "AW",
	"Australia": "AU",
	"Austria": "AT",
	"Azerbaijan": "AZ",
	"Bahamas": "BS",
	"Bahrain": "BH",
	"Bangladesh": "BD",
	"Barbados": "BB",
	"Belarus": "BY",
	"Belgium": "BE",
	"Belize": "BZ",
	"Benin": "BJ",
	"Bermuda": "BM",
	"Bolivia": "BO",
	"Bonaire": "BQ",
	"Bosnia and Herzegovina": "BA",
	"Botswana": "BW",
	"Bouvet Island": "BV",
	"Brazil": "BR",
	"Bulgaria": "BG",
	"Burkina Faso": "BF",
	"Burundi": "BI",
	"Cameroon": "CM",
	"Canada": "CA",
	"Cape Verde": "CV",
	"Cayman Islands": "KY",
	"Central African Republic": "CF",
	"Chad": "TD",
	"Chile": "CL",
	"China": "CN",
	"Colombia": "CO",
	"Comoros": "KM",
	"Congo": "CG",
	"Costa Rica": "CR",
	"Cote d'Ivoire": "CI",
	"Croatia": "HR",
	"Cuba": "CU",
	"Curaçao": "CW",
	"Czech Republic": "CZ",
	"Democratic Republic of Congo": "CD",
	"Denmark": "DK",
	"Djibouti": "DJ",
	"Dominica": "DM",
	"Dominican Republic": "DO",
	"Ecuador": "EC",
	"Egypt": "EG",
	"El Salvador": "SV",
	"Equatorial Guinea": "GQ",
	"Eritrea": "ER",
	"Estonia": "EE",
	"Ethiopia": "ET",
	"Europe-Other": "EUO",
	"Falkland Islands (Malvinas)": "FK",
	"Faroe Islands (Denmark)": "FO",
	"Finland": "FI",
	"France": "FR",
	"French Guiana": "GF",
	"French Southern Territories": "TF",
	"Gabon": "GA",
	"Gambia": "GM",
	"Georgia": "GE",
	"Germany": "DE",
	"Ghana": "GH",
	"Gibraltar (UK)": "GI",
	"Global": "RW",
	"Greece": "GR",
	"Greenland": "GL",
	"Grenada": "GD",
	"Guadeloupe": "GP",
	"Guatemala": "GT",
	"Guinea": "GN",
	"Guinea-Bissau": "GW",
	"Guyana": "GY",
	"Haiti": "HT",
	"Heard Island and McDonald Islands": "HM",
	"Honduras": "HN",
	"Hong Kong": "HK",
	"Hungary": "HU",
	"Iceland": "IS",
	"India": "IN",
	"Indonesia": "ID",
	"Iraq": "IQ",
	"Ireland": "IE",
	"Israel": "IL",
	"Italy": "IT",
	"Jamaica": "JM",
	"Jordan": "JO",
	"Kenya": "KE",
	"Kuwait": "KW",
	"Latvia": "LV",
	"Lebanon": "LB",
	"Lesotho": "LS",
	"Liberia": "LR",
	"Libya": "LY",
	"Liechtenstein": "LI",
	"Lithuania": "LT",
	"Luxembourg": "LU",
	"Macedonia": "MK",
	"Madagascar": "MG",
	"Malawi": "MW",
	"Malaysia": "MY",
	"Mali": "ML",
	"Malta": "MT",
	"Martinique": "MQ",
	"Mauritania": "MR",
	"Mauritius": "MU",
	"Mayotte": "YT",
	"Mexico": "MX",
	"Moldova": "MD",
	"Monaco": "MC",
	"Montserrat": "MS",
	"Morocco": "MA",
	"Mozambique": "MZ",
	"Namibia": "NA",
	"Netherlands": "NL",
	"New Caledonia": "NC",
	"New Zealand": "NZ",
	"Nicaragua": "NI",
	"Niger": "NE",
	"Nigeria": "NG",
	"Norfolk Island": "NF",
	"Northern Ireland": "GB",
	"Norway": "NO",
	"Oman": "OM",
	"Palestinian Territory": "PS",
	"Panama": "PA",
	"Paraguay": "PY",
	"Peru": "PE",
	"Philippines": "PH",
	"Poland": "PL",
	"Portugal": "PT",
	"Qatar": "QA",
	"Reunion": "RE",
	"Romania": "RO",
	"Russian Federation": "RU",
	"Rwanda": "RW",
	"Saint Barthélemy": "BL",
	"Saint Helena, Ascension and Tristan da Cunha": "SH",
	"Saint Kitts and Nevis": "KN",
	"Saint Lucia": "LC",
	"Saint Martin (French part)": "MF",
	"Saint Pierre and Miquelon": "PM",
	"Saint Vincent and the Grenadines": "VC",
	"San Marino": "SM",
	"Sao Tome and Principe": "ST",
	"Saudi Arabia": "SA",
	"Senegal": "SN",
	"Serbia": "RS",
	"Seychelles": "SC",
	"Sierra Leone": "SL",
	"Singapore": "SG",
	"Sint Maarten (Dutch part)": "SX",
	"Slovakia": "SK",
	"Slovenia": "SI",
	"Somalia": "SO",
	"South Africa": "ZA",
	"South Georgia and the South Sandwich Islands": "GS",
	"South Sudan": "SS",
	"Spain": "ES",
	"Sudan": "SD",
	"Suriname": "SR",
	"Svalbard and Jan Mayen": "SJ",
	"Swaziland": "SZ",
	"Sweden": "SE",
	"Switzerland": "CH",
	"Syria": "SY",
	"Tanzania": "TZ",
	"Thailand": "TH",
	"Togo": "TG",
	"Tokelau": "TK",
	"Trinidad and Tobago": "TT",
	"Tunisia": "TN",
	"Turkey": "TR",
	"Turks and Caicos Islands": "TC",
	"UAE": "AE",
	"Uganda": "UG",
	"Ukraine": "UA",
	"United Kingdom": "UK",
	"United States": "US",
	"Uruguay": "UY",
	"Vatican City": "VA",
	"Venezuela": "VE",
	"Vietnam": "VN",
	"Wallis and Futuna": "WF",
	"Western Sahara": "EH",
	"Yemen": "YE",
	"Zambia": "ZM",
	"Zimbabwe": "ZW"
}