export const GeolocationAndCountries = {

    "North America": [
        "Canada",
        "United States"
    ],

    "UK & Ireland": [
        "Ireland",
        "United Kingdom",
        "Northern Ireland"
    ],

    "DACH": [
        "Austria",
        "Germany",
        "Switzerland",
        "Liechtenstein"
    ],

    "France & Belgium": [
        "Belgium",
        "France",
        "Luxembourg"
    ],

    "APAC": [
        "Australia",
        "China",
        "Hong Kong",
        "India",
        "New Zealand",
        "Singapore",
        "Thailand",
        "Vietnam",
        "Indonesia",
        "Malaysia",
        "Philippines"
    ],

    "GM - EME": [
        "Albania",
        "Andorra",
        "Belarus",
        "Bulgaria",
        "Croatia",
        "Czech Republic",
        "Denmark",
        "Estonia",
        "Finland",
        "Greece",
        "Hungary",
        "Iceland",
        "Italy",
        "Latvia",
        "Lithuania",
        "Macedonia",
        "Malta",
        "Moldova",
        "Monaco",
        "Netherlands",
        "Norway",
        "Poland",
        "Portugal",
        "Romania",
        "Serbia",
        "Slovakia",
        "Slovenia",
        "Spain",
        "Sweden",
        "Ukraine",
        "Turkey",
        "Vatican City",
        "Qatar",
        "Saudi Arabia",
        "UAE"
    ],

    "Rest of World": [
        "Afghanistan",
        "Aland Islands",
        "Algeria",
        "Angola",
        "Anguilla",
        "Antarctica",
        "Antigua&Barbuda",
        "Argentina",
        "Armenia",
        "Aruba",
        "Azerbaijan",
        "Bahamas",
        "Bahrain",
        "Bangladesh",
        "Barbados",
        "Belize",
        "Benin",
        "Bermuda",
        "Bolivia",
        "Bonaire",
        "Bosnia and Herzegovina",
        "Botswana",
        "Bouvet Island",
        "Brazil",
        "Burkina Faso",
        "Burundi",
        "Cameroon",
        "Cape Verde",
        "Cayman Islands",
        "Central African Republic",
        "Chad",
        "Chile",
        "Colombia",
        "Comoros",
        "Congo",
        "Costa Rica",
        "Cote d'Ivoire",
        "Cuba",
        "Curaçao",
        "Congo",
        "Djibouti",
        "Dominica",
        "Dominican Republic",
        "Ecuador",
        "Egypt",
        "El Salvador",
        "Equatorial Guinea",
        "Eritrea",
        "Ethiopia",
        "Falkland Islands",
        "Faroe Islands",
        "French Guiana",
        "French Southern Territories",
        "Gabon",
        "Gambia",
        "Georgia",
        "Ghana",
        "Gibraltar (UK)",
        "Greenland",
        "Grenada",
        "Guadeloupe",
        "Guatemala",
        "Guinea",
        "Guinea-Bissau",
        "Guyana",
        "Haiti",
        "Heard Island and McDonald Islands",
        "Honduras",
        "Iraq",
        "Israel",
        "Jamaica",
        "Jordan",
        "Kenya",
        "Kuwait",
        "Lebanon",
        "Lesotho",
        "Liberia",
        "Libya",
        "Madagascar",
        "Malawi",
        "Mali",
        "Martinique",
        "Mauritania",
        "Mauritius",
        "Mayotte",
        "Mexico",
        "Montserrat",
        "Morocco",
        "Mozambique",
        "Namibia",
        "New Caledonia",
        "Nicaragua",
        "Niger",
        "Nigeria",
        "Norfolk Island",
        "Oman",
        "Palestinian Territory",
        "Panama",
        "Paraguay",
        "Peru",
        "Reunion",
        "Russia",
        "Rwanda",
        "Saint Barthélemy",
        "Saint Helena",
        "Saint Kitts and Nevis",
        "Saint Lucia",
        "Saint Martin (French part)",
        "Saint Pierre and Miquelon",
        "Saint Vincent and the Grenadines",
        "San Marino",
        "Sao Tome and Principe",
        "Senegal",
        "Seychelles",
        "Sierra Leone",
        "Sint Maarten (Dutch part)",
        "Somalia",
        "South Africa",
        "South Georgia and the South Sandwich Islands",
        "South Sudan",
        "Sudan",
        "Suriname",
        "Svalbard and Jan Mayen",
        "Swaziland",
        "Syria",
        "Tanzania",
        "Togo",
        "Tokelau",
        "Trinidad and Tobago",
        "Tunisia",
        "Turks and Caicos Islands",
        "Uganda",
        "Uruguay",
        "Venezuela",
        "Wallis and Futuna",
        "Western Sahara",
        "Yemen",
        "Zambia",
        "Zimbabwe"
    ]
}