export enum NotificationEventType {
	LEAD_REJECTED = "LEAD_REJECTED",
	ACCREDITATION_UPDATED = "ACCREDITATION_UPDATED",
	LEAD_CONVERTED_TO_OPPORTUNITY = "LEAD_CONVERTED_TO_OPPORTUNITY",
	OPPORTUNITY_UPDATED = "OPPORTUNITY_UPDATED",
	OPPORTUNITY_REMOVED_FROM_AP = "OPPORTUNITY_REMOVED_FROM_AP",
	SCORING_CRITERIA_UPDATED = "SCORING_CRITERIA_UPDATED",
}

export enum NotificationObjectType {
	LEAD = "LEAD",
	ACCREDITATION = "ACCREDITATION",
	CERTIFICATION = "CERTIFICATION",
	SCORING_CRITERIA = "SCORING_CRITERIA",
}