export enum recordTypeEnvKeys {
    "SFDC_RECORD_TYPE_BUILDINGS" = "SFDC_RECORD_TYPE_BUILDINGS",
    "SFDC_RECORD_TYPE_COMPANIES" = "SFDC_RECORD_TYPE_COMPANIES",
    "SFDC_RECORD_TYPE_DEVELOPMENT" = "SFDC_RECORD_TYPE_DEVELOPMENT",
    "SFDC_RECORD_TYPE_OCCUPIED" = "SFDC_RECORD_TYPE_OCCUPIED",
    "SFDC_RECORD_TYPE_RENEWAL" = "SFDC_RECORD_TYPE_RENEWAL"
}